### ISSUE TITLE
Work

### ISSUE THREAD

**Issue by koaser1324** [Daszbin/HackBrowserDataCSharp#1]
Can you offer more explanation about your work
And the problems your are facing I'm here to help you.

**Comment by Daszbin** [comment]
So the code is to grab passwords, bookmarks, extensions, history, cookies from all the major browsers and print them out as csv or json. The problem im facing is when i open the program its closes automatically unlike moonD4rk version of HackBrowserData which opens but its written in GO. So i need it to actually work.

**Comment by koaser1324** [comment]
Do you have telegram so we can discuss better.
@Mohannad1111111 my telegram identifier.

Have you try to run the program inside IDL and track what happens and lead to close the program.
And in the current version do you get any results when run the program?

**Comment by Daszbin** [comment]
no i havent tried it i tried converting it from golang to c# with chatgpt to no success

**Comment by Daszbin** [comment]
my telegram is daszbin

**Comment by Daszbin** [comment]
This is figured out

**Comment by Daszbin** [comment]
this is figured out
